version: "3"

services:
  rag_example:
    container_name: rag_example
    restart: no
    ports:
      - 8501:8501
    volumes:
      - .:/app
    build:
      context: "."
      dockerfile: Dockerfile